[build]
target = "xtensa-esp32-espidf"

[target.xtensa-esp32-espidf]
linker = "ldproxy"
runner = "espflash flash --monitor"
rustflags = ["--cfg", "espidf_time64"]

[unstable]
build-std = ["std", "panic_abort"]

[env]
ESP_IDF_VERSION = { value = "v5.2.3" }
# Reduce verbosity
ESP_IDF_LOG_LEVEL = { value = "info" }
# Use system Python
ESP_IDF_TOOLS_INSTALL_DIR = { value = "global" }
